spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 1234
    initialization-mode: always
    schema: classpath:h2/schema.sql
    data: classpath:h2/data.sql