DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
    ID INT AUTO_INCREMENT,
    EMAIL VARCHAR(30),
    PASSWORD VARCHAR(255),
    USERTYPE VARCHAR(30),
    CREATEDAT DATETIME,
    UPDATEDAT DATETIME ,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS DISPATCH;
CREATE TABLE DISPATCH(
    ID INT PRIMARY KEY,
    ADDRESS VARCHAR(50),
    DRIVERID INT,
    PASSENGERID INT,
    STATUS VARCHAR(8),
    ACCEPTEDAT DATE,
    CREATEDAT DATE,
    UPDATEDAT DATE,
    FOREIGN KEY (DRIVERID) REFERENCES USER(ID),
    FOREIGN KEY (PASSENGERID) REFERENCES USER(ID)
);
